import { FabricProduct, Order, Lead, InventoryRoll, User } from "@/types";

export const MOCK_USERS: User[] = [
  {
    id: "usr-1",
    name: "Hendra Wijaya",
    email: "hendra@garmentkreatif.com",
    role: "CUSTOMER",
    companyName: "PT. Garment Kreatif Nusantara",
    phoneNumber: "081234567890",
    taxId: "01.234.567.8-012.000",
  },
  {
    id: "usr-2",
    name: "Rian Pratama",
    email: "rian.sales@texora.co.id",
    role: "SALES_REP",
    companyName: "PT. Texora Visi Prima",
    phoneNumber: "081298765432",
  },
  {
    id: "usr-3",
    name: "Bambang Santoso",
    email: "bambang.wh@texora.co.id",
    role: "WAREHOUSE_STAFF",
    companyName: "PT. Texora Visi Prima",
    phoneNumber: "081377889900",
  },
  {
    id: "usr-4",
    name: "Dian Sastrawan",
    email: "admin@texora.co.id",
    role: "ADMINISTRATOR",
    companyName: "PT. Texora Visi Prima",
    phoneNumber: "081122334455",
  },
];

export const MOCK_FABRICS: FabricProduct[] = [
  // ── 1. SPORTSWEAR & ACTIVEWEAR ──────────────────────────────────────
  {
    id: "fab-1",
    name: "Dryfit Milano Premium",
    slug: "dryfit-milano-premium",
    category: "Sportswear",
    description: "Kain rajut bertekstur bintik halus dengan sirkulasi udara maksimal. Formula khusus penyerapan tinta sublimasi warna pekat, anti-luntur, dan cepat kering (quick-dry). Pilihan utama untuk jersey sepak bola, sepeda, dan running.",
    composition: "100% Micro Polyester",
    weaveType: "Circular Knit Eyelet (Bintik Beras)",
    widthInch: 60,
    isSublimationReady: true,
    basePricePerMeter: 36000,
    thumbnailUrl: "https://images.unsplash.com/photo-1558769132-cb1aea458c5e?auto=format&fit=crop&w=800&q=80",
    variants: [
      { id: "var-1", gsm: 135, colorName: "Optic White Ready Sublim", stockMeters: 4500 },
      { id: "var-2", gsm: 155, colorName: "Optic White Heavy Sublim", stockMeters: 2800 },
    ],
    priceTiers: [
      { id: "tier-1", minMeters: 1, maxMeters: 49, unitPrice: 36000 },
      { id: "tier-2", minMeters: 50, maxMeters: 199, unitPrice: 32500 },
      { id: "tier-3", minMeters: 200, maxMeters: 999, unitPrice: 29000 },
      { id: "tier-4", minMeters: 1000, maxMeters: undefined, unitPrice: 26500 },
    ],
  },
  {
    id: "fab-2",
    name: "Dryfit Brazil Wave Hexagon",
    slug: "dryfit-brazil-wave",
    category: "Sportswear",
    description: "Kain jersey premium dengan rajutan pola heksagonal mikro elastis. Sangat fleksibel, ringan, dan memberikan sensasi dingin (cooling touch) saat berkeringat. Menjadi standar jersey tim pro e-sport, motocross, dan basket.",
    composition: "100% Microfilament Poly",
    weaveType: "Hexagonal Geometric Knit",
    widthInch: 60,
    isSublimationReady: true,
    basePricePerMeter: 37500,
    thumbnailUrl: "https://images.unsplash.com/photo-1578932750294-f5075e85f44a?auto=format&fit=crop&w=800&q=80",
    variants: [
      { id: "var-3", gsm: 130, colorName: "Pure White Sublim", stockMeters: 3800 },
      { id: "var-4", gsm: 145, colorName: "Pure White High-Density", stockMeters: 2200 },
    ],
    priceTiers: [
      { id: "tier-5", minMeters: 1, maxMeters: 49, unitPrice: 37500 },
      { id: "tier-6", minMeters: 50, maxMeters: 199, unitPrice: 34000 },
      { id: "tier-7", minMeters: 200, maxMeters: 999, unitPrice: 30500 },
      { id: "tier-8", minMeters: 1000, maxMeters: undefined, unitPrice: 27800 },
    ],
  },
  {
    id: "fab-3",
    name: "Dryfit Jarum (Needle-Drop) QuickDry",
    slug: "dryfit-jarum-quickdry",
    category: "Sportswear",
    description: "Kain dengan lubang pori mikro teratur menyerupai tusukan jarum halus. Dirancang khusus untuk ventilasi udara intensif, bobot sangat ringan, dan tidak menempel di tubuh saat basah. Sangat diminati untuk jersey lari marathon dan roadbike.",
    composition: "100% Polyester Filament",
    weaveType: "Micro Pin-Hole Airflow Mesh",
    widthInch: 60,
    isSublimationReady: true,
    basePricePerMeter: 35000,
    thumbnailUrl: "https://images.unsplash.com/photo-1509631179647-0177331693ae?auto=format&fit=crop&w=800&q=80",
    variants: [
      { id: "var-5", gsm: 140, colorName: "Optic White", stockMeters: 5200 },
      { id: "var-6", gsm: 160, colorName: "Bright White", stockMeters: 3400 },
    ],
    priceTiers: [
      { id: "tier-9", minMeters: 1, maxMeters: 49, unitPrice: 35000 },
      { id: "tier-10", minMeters: 50, maxMeters: 199, unitPrice: 31500 },
      { id: "tier-11", minMeters: 200, maxMeters: 999, unitPrice: 28000 },
      { id: "tier-12", minMeters: 1000, maxMeters: undefined, unitPrice: 25500 },
    ],
  },
  {
    id: "fab-4",
    name: "Drifit Polymesh Ventilasi Pro",
    slug: "drifit-polymesh-pro",
    category: "Sportswear",
    description: "Kain jala mikro berkekuatan tarik tinggi untuk aplikasi ventilasi zona khusus (ketiak, punggung, dan sisi samping baju olahraga). Mampu mentransfer uap panas tubuh secara instan dengan daya tahan cuci tinggi.",
    composition: "100% High-Tenacity Poly",
    weaveType: "Ultra-Light Aerated Mesh",
    widthInch: 58,
    isSublimationReady: true,
    basePricePerMeter: 33000,
    thumbnailUrl: "https://images.unsplash.com/photo-1584917865442-de89df76afd3?auto=format&fit=crop&w=800&q=80",
    variants: [
      { id: "var-7", gsm: 110, colorName: "Optic White Mesh", stockMeters: 4100 },
    ],
    priceTiers: [
      { id: "tier-13", minMeters: 1, maxMeters: 49, unitPrice: 33000 },
      { id: "tier-14", minMeters: 50, maxMeters: 199, unitPrice: 29500 },
      { id: "tier-15", minMeters: 200, maxMeters: 999, unitPrice: 26500 },
      { id: "tier-16", minMeters: 1000, maxMeters: undefined, unitPrice: 24000 },
    ],
  },
  {
    id: "fab-5",
    name: "Scuba Neoprene Stretch Heavy",
    slug: "scuba-neoprene-stretch-heavy",
    category: "Sportswear",
    description: "Kain scuba tebal dua sisi (double-knit) dengan struktur elastis dan kokoh. Tahan kusut, tidak menerawang, dan memberikan efek timbul tegas saat dipress sublimasi. Populer untuk jaket bomber, rok struktural, masker premium, dan sarung bantal.",
    composition: "95% Polyester, 5% Spandex",
    weaveType: "Double Knit Interlock",
    widthInch: 60,
    isSublimationReady: true,
    basePricePerMeter: 48000,
    thumbnailUrl: "https://images.unsplash.com/photo-1579783900882-c0d3dad7b119?auto=format&fit=crop&w=800&q=80",
    variants: [
      { id: "var-8", gsm: 260, colorName: "Optic White", stockMeters: 2400 },
      { id: "var-9", gsm: 290, colorName: "Raw White", stockMeters: 1600 },
    ],
    priceTiers: [
      { id: "tier-17", minMeters: 1, maxMeters: 49, unitPrice: 48000 },
      { id: "tier-18", minMeters: 50, maxMeters: 199, unitPrice: 44000 },
      { id: "tier-19", minMeters: 200, maxMeters: 999, unitPrice: 40500 },
      { id: "tier-20", minMeters: 1000, maxMeters: undefined, unitPrice: 37000 },
    ],
  },
  {
    id: "fab-6",
    name: "Spandex Lycra Swim & Athletic",
    slug: "spandex-lycra-athletic",
    category: "Sportswear",
    description: "Kain 4-way stretch lentur dengan pemulihan elastisitas luar biasa. Tahan kaporit dan sinar UV, permukaan padat anti-pecah saat ditarik. Digunakan oleh produsen baju renang, legging yoga, manset, dan pakaian olahraga kompresi.",
    composition: "82% Poly-Dull, 18% Elastane",
    weaveType: "Tricot Warp Knit 4-Way Stretch",
    widthInch: 60,
    isSublimationReady: true,
    basePricePerMeter: 55000,
    thumbnailUrl: "https://images.unsplash.com/photo-1544441893-675973e31985?auto=format&fit=crop&w=800&q=80",
    variants: [
      { id: "var-10", gsm: 210, colorName: "Bright White Sublim", stockMeters: 1800 },
      { id: "var-11", gsm: 240, colorName: "Matte White Sublim", stockMeters: 1200 },
    ],
    priceTiers: [
      { id: "tier-21", minMeters: 1, maxMeters: 49, unitPrice: 55000 },
      { id: "tier-22", minMeters: 50, maxMeters: 199, unitPrice: 51000 },
      { id: "tier-23", minMeters: 200, maxMeters: 999, unitPrice: 47000 },
      { id: "tier-24", minMeters: 1000, maxMeters: undefined, unitPrice: 43500 },
    ],
  },

  // ── 2. FASHION & HIJAB ISLAMI ───────────────────────────────────────
  {
    id: "fab-7",
    name: "Voal Ultrafine Premium Hijab",
    slug: "voal-ultrafine-premium",
    category: "Fashion & Hijab",
    description: "Kain voal ultrafine bertekstur katun lembut, adem, tegak di dahi dan tidak pekak di telinga. Hasil sublimasi tembus dua sisi hingga 85% dengan warna pastel maupun bold. Pilihan nomor satu untuk hijab printing segiempat, scarf motif floral islami, dan kerudung muslimah.",
    composition: "100% Poly-Voal Ultrafine",
    weaveType: "Airy Plain Weave",
    widthInch: 46,
    isSublimationReady: true,
    basePricePerMeter: 31000,
    thumbnailUrl: "/images/fabrics/voal-ultrafine-hijab.jpg",
    variants: [
      { id: "var-12", gsm: 85, colorName: "Optic White", stockMeters: 6200 },
      { id: "var-13", gsm: 95, colorName: "Natural Off-White", stockMeters: 4500 },
    ],
    priceTiers: [
      { id: "tier-25", minMeters: 1, maxMeters: 49, unitPrice: 31000 },
      { id: "tier-26", minMeters: 50, maxMeters: 199, unitPrice: 28000 },
      { id: "tier-27", minMeters: 200, maxMeters: 999, unitPrice: 25000 },
      { id: "tier-28", minMeters: 1000, maxMeters: undefined, unitPrice: 22500 },
    ],
  },
  {
    id: "fab-8",
    name: "Polyester Silk Satin Silk",
    slug: "polyester-silk-satin",
    category: "Fashion & Hijab",
    description: "Kain satin polyester dengan kilau sutra mewah, permukaan sangat licin dan drape jatuh anggun. Menghasilkan kontras warna sublimasi arabesque dan floral islami dengan ketajaman gradasi tinggi. Sangat cocok untuk hijab pashmina satin, scarf eksklusif, dan gaun muslimah pesta.",
    composition: "100% Filament Polyester",
    weaveType: "High Density Satin Weave",
    widthInch: 58,
    isSublimationReady: true,
    basePricePerMeter: 42000,
    thumbnailUrl: "/images/fabrics/satin-silk-hijab.jpg",
    variants: [
      { id: "var-14", gsm: 95, colorName: "Super White Gloss", stockMeters: 3200 },
      { id: "var-15", gsm: 115, colorName: "Pearl White Gloss", stockMeters: 1900 },
    ],
    priceTiers: [
      { id: "tier-29", minMeters: 1, maxMeters: 49, unitPrice: 42000 },
      { id: "tier-30", minMeters: 50, maxMeters: 199, unitPrice: 38000 },
      { id: "tier-31", minMeters: 200, maxMeters: 999, unitPrice: 34500 },
      { id: "tier-32", minMeters: 1000, maxMeters: undefined, unitPrice: 31000 },
    ],
  },
  {
    id: "fab-9",
    name: "Armani Silk Royal Sheen (Kemeja Koko & Busana Muslim)",
    slug: "armani-silk-royal",
    category: "Fashion & Hijab",
    description: "Kain sutra sintetis kelas haute-couture dengan sentuhan dingin mewah, flowy lembut, dan kilau matte maskulin yang berkelas. Menjadi primadona untuk kemeja koko pria modern, busana muslim pria Idul Fitri, gamis sutra dingin, serta pashmina printing monogram.",
    composition: "97% Micro Poly-Silk, 3% Spandex",
    weaveType: "Ultra-Fine Dobby Satin",
    widthInch: 58,
    isSublimationReady: true,
    basePricePerMeter: 46000,
    thumbnailUrl: "/images/fabrics/kemeja-koko-islami.jpg",
    variants: [
      { id: "var-16", gsm: 100, colorName: "Pure Pearl Silk", stockMeters: 2800 },
    ],
    priceTiers: [
      { id: "tier-33", minMeters: 1, maxMeters: 49, unitPrice: 46000 },
      { id: "tier-34", minMeters: 50, maxMeters: 199, unitPrice: 42000 },
      { id: "tier-35", minMeters: 200, maxMeters: 999, unitPrice: 38500 },
      { id: "tier-36", minMeters: 1000, maxMeters: undefined, unitPrice: 35000 },
    ],
  },
  {
    id: "fab-10",
    name: "Chiffon Ceruty Babydoll Sublim (Khimar & Gamis Syari)",
    slug: "chiffon-ceruty-babydoll",
    category: "Fashion & Hijab",
    description: "Kain sifon ceruty bertekstur pasir lembut, jatuh menjuntai (flowy), sangat sejuk dan anggun. Menghasilkan efek warna sublimasi bernuansa pastel lembut dan syari. Pilihan utama untuk khimar syari layer ganda, gamis outer muslimah, dan jilbab instan.",
    composition: "100% Textured Poly-Chiffon",
    weaveType: "Crepe Georgette Weave",
    widthInch: 58,
    isSublimationReady: true,
    basePricePerMeter: 28500,
    thumbnailUrl: "/images/fabrics/chiffon-khimar-syari.jpg",
    variants: [
      { id: "var-17", gsm: 75, colorName: "Pure Bleached White", stockMeters: 5500 },
    ],
    priceTiers: [
      { id: "tier-37", minMeters: 1, maxMeters: 49, unitPrice: 28500 },
      { id: "tier-38", minMeters: 50, maxMeters: 199, unitPrice: 25500 },
      { id: "tier-39", minMeters: 200, maxMeters: 999, unitPrice: 22500 },
      { id: "tier-40", minMeters: 1000, maxMeters: undefined, unitPrice: 19800 },
    ],
  },
  {
    id: "fab-11",
    name: "Shakila Twill Stretch Flowy (Tunik & One-Set Muslimah)",
    slug: "shakila-twill-stretch",
    category: "Fashion & Hijab",
    description: "Kain tenun diagonal (twill) agak lentur dengan permukaan halus menyerupai katun, tidak menerawang dan sangat adem. Sangat ideal untuk tunik muslimah modern, setelan one-set islami, kemeja kerja syari, dan celana kulot printing motif etnik.",
    composition: "92% Poly, 8% Elastane",
    weaveType: "Diagonal Fine Twill",
    widthInch: 58,
    isSublimationReady: true,
    basePricePerMeter: 39000,
    thumbnailUrl: "/images/fabrics/shakila-tunik-muslimah.jpg",
    variants: [
      { id: "var-18", gsm: 165, colorName: "Bright Milk White", stockMeters: 3600 },
    ],
    priceTiers: [
      { id: "tier-41", minMeters: 1, maxMeters: 49, unitPrice: 39000 },
      { id: "tier-42", minMeters: 50, maxMeters: 199, unitPrice: 35000 },
      { id: "tier-43", minMeters: 200, maxMeters: 999, unitPrice: 31500 },
      { id: "tier-44", minMeters: 1000, maxMeters: undefined, unitPrice: 28500 },
    ],
  },

  // ── 3. HOME LIVING & INTERIOR ───────────────────────────────────────
  {
    id: "fab-12",
    name: "Canvas Polyester 8oz (Bantal Sofa & Home Decor)",
    slug: "canvas-polyester-industrial",
    category: "Home Living",
    description: "Kain kanvas poliester bertekstur anyaman benang tegas, kokoh dan tahan abrasi. Menghasilkan warna cetak sublimasi cerah dengan detail botanical tajam. Pilihan utama untuk sarung bantal sofa living room, taplak meja, tote bag estetis, dan kanvas lukis dinding.",
    composition: "100% Spun Polyester Canvas",
    weaveType: "Plain Weave 2x2",
    widthInch: 58,
    isSublimationReady: true,
    basePricePerMeter: 39000,
    thumbnailUrl: "/images/fabrics/canvas-cushion-interior.jpg",
    variants: [
      { id: "var-19", gsm: 240, colorName: "Natural Off-White", stockMeters: 3100 },
      { id: "var-20", gsm: 280, colorName: "Bleached Pure White", stockMeters: 2200 },
    ],
    priceTiers: [
      { id: "tier-45", minMeters: 1, maxMeters: 49, unitPrice: 39000 },
      { id: "tier-46", minMeters: 50, maxMeters: 199, unitPrice: 35000 },
      { id: "tier-47", minMeters: 200, maxMeters: 999, unitPrice: 31500 },
      { id: "tier-48", minMeters: 1000, maxMeters: undefined, unitPrice: 28500 },
    ],
  },
  {
    id: "fab-13",
    name: "Velvet Velboa Premium Plush (Bantal & Selimut Sofa)",
    slug: "velvet-velboa-plush",
    category: "Home Living",
    description: "Kain beludru dengan tumpukan bulu mikro padat, sangat lembut dan berkilau mewah di bawah pencahayaan ruangan. Menjadi pilihan favorit untuk bantal sofa mewah (luxury velvet cushions), selimut sofa printing (throw blanket), tapestry dinding artistik, dan furnitur upholstery.",
    composition: "100% Poly Pile Microfiber",
    weaveType: "Warp Knitted Pile Velvet",
    widthInch: 60,
    isSublimationReady: true,
    basePricePerMeter: 45000,
    thumbnailUrl: "/images/fabrics/velvet-pillow-throw.jpg",
    variants: [
      { id: "var-21", gsm: 220, colorName: "Bright Snow White", stockMeters: 2100 },
      { id: "var-22", gsm: 260, colorName: "Optic Velvet White", stockMeters: 1500 },
    ],
    priceTiers: [
      { id: "tier-49", minMeters: 1, maxMeters: 49, unitPrice: 45000 },
      { id: "tier-50", minMeters: 50, maxMeters: 199, unitPrice: 41000 },
      { id: "tier-51", minMeters: 200, maxMeters: 999, unitPrice: 37500 },
      { id: "tier-52", minMeters: 1000, maxMeters: undefined, unitPrice: 34000 },
    ],
  },
  {
    id: "fab-14",
    name: "Blackout Curtain 3-Pass Thermal (Gorden Hotel & Villa)",
    slug: "blackout-curtain-thermal",
    category: "Home Living",
    description: "Kain gorden ekstra lebar 110 inci dengan struktur 3-lapisan anyaman peredam hitam. Mampu menahan 100% cahaya matahari, isolasi suhu ruang dingin, serta mereduksi pantulan suara. Standar rujukan proyek interior gorden hotel berbintang, villa, dan kamar tidur mewah.",
    composition: "100% Poly Triple-Weave Blackout",
    weaveType: "High Density Triple Weave",
    widthInch: 110,
    isSublimationReady: true,
    basePricePerMeter: 68000,
    thumbnailUrl: "/images/fabrics/blackout-curtain-luxury.jpg",
    variants: [
      { id: "var-23", gsm: 280, colorName: "Pure White Face / Blackout Core", stockMeters: 1800 },
    ],
    priceTiers: [
      { id: "tier-53", minMeters: 1, maxMeters: 49, unitPrice: 68000 },
      { id: "tier-54", minMeters: 50, maxMeters: 199, unitPrice: 63000 },
      { id: "tier-55", minMeters: 200, maxMeters: 999, unitPrice: 57500 },
      { id: "tier-56", minMeters: 1000, maxMeters: undefined, unitPrice: 52000 },
    ],
  },
  {
    id: "fab-15",
    name: "Microfiber Suede Quick-Absorb (Handuk & Matras Spa)",
    slug: "microfiber-suede-absorb",
    category: "Home Living",
    description: "Kain microfiber suede dengan daya serap air ultra-tinggi dan handfeel selembut beludru tanpa melukai permukaan sensitif. Hasil cetak warna cerah dan tajam. Cocok untuk handuk mandi hotel kustom, handuk pantai spa, matras yoga suede, dan lap kacamata optik.",
    composition: "80% Poly, 20% Polyamide",
    weaveType: "Split Microfiber Terry Knit",
    widthInch: 60,
    isSublimationReady: true,
    basePricePerMeter: 44000,
    thumbnailUrl: "/images/fabrics/microfiber-towel-mat.jpg",
    variants: [
      { id: "var-24", gsm: 250, colorName: "Optic White", stockMeters: 2900 },
    ],
    priceTiers: [
      { id: "tier-57", minMeters: 1, maxMeters: 49, unitPrice: 44000 },
      { id: "tier-58", minMeters: 50, maxMeters: 199, unitPrice: 40000 },
      { id: "tier-59", minMeters: 200, maxMeters: 999, unitPrice: 36500 },
      { id: "tier-60", minMeters: 1000, maxMeters: undefined, unitPrice: 33000 },
    ],
  },

  // ── 4. MERCHANDISE, FLAGS & INDUSTRIAL ──────────────────────────────
  {
    id: "fab-16",
    name: "Taffeta Parachute Ripstop Light",
    slug: "taffeta-parachute-ripstop",
    category: "Merchandise & Flag",
    description: "Kain parasut ultra-ringan dengan rajutan kotak ripstop anti-robek. Tahan terpaan angin kencang dan cuaca luar ruangan. Solusi nomor satu untuk bendera instansi, umbul-umbul promosi, serta jaket windbreaker travel.",
    composition: "100% High-Density Polyester",
    weaveType: "Ripstop Grid Weave",
    widthInch: 60,
    isSublimationReady: true,
    basePricePerMeter: 26000,
    thumbnailUrl: "https://images.unsplash.com/photo-1506152983158-b4a74a01c721?auto=format&fit=crop&w=800&q=80",
    variants: [
      { id: "var-25", gsm: 65, colorName: "Optic White Ripstop", stockMeters: 8500 },
      { id: "var-26", gsm: 80, colorName: "Super White Dense", stockMeters: 4200 },
    ],
    priceTiers: [
      { id: "tier-61", minMeters: 1, maxMeters: 49, unitPrice: 26000 },
      { id: "tier-62", minMeters: 50, maxMeters: 199, unitPrice: 23000 },
      { id: "tier-63", minMeters: 200, maxMeters: 999, unitPrice: 20500 },
      { id: "tier-64", minMeters: 1000, maxMeters: undefined, unitPrice: 18000 },
    ],
  },
  {
    id: "fab-17",
    name: "Polyester Oxford 600D Heavy Duty",
    slug: "polyester-oxford-600d",
    category: "Merchandise & Flag",
    description: "Kain tenun anyaman keranjang 600 Denier dengan pelapis PU tahan air di bagian belakang. Struktur kokoh, tahan gesek dan tidak gampang melar. Cocok untuk tas ransel laptop, tas koper kargo, tenda promosi lipat, dan booth pameran.",
    composition: "100% Filament Polyester PU Backing",
    weaveType: "Oxford Basket Weave 600D",
    widthInch: 58,
    isSublimationReady: true,
    basePricePerMeter: 49000,
    thumbnailUrl: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=800&q=80",
    variants: [
      { id: "var-27", gsm: 340, colorName: "Natural Off-White", stockMeters: 3300 },
    ],
    priceTiers: [
      { id: "tier-65", minMeters: 1, maxMeters: 49, unitPrice: 49000 },
      { id: "tier-66", minMeters: 50, maxMeters: 199, unitPrice: 45000 },
      { id: "tier-67", minMeters: 200, maxMeters: 999, unitPrice: 41000 },
      { id: "tier-68", minMeters: 1000, maxMeters: undefined, unitPrice: 37500 },
    ],
  },
  {
    id: "fab-18",
    name: "TC Sublimasi Cotton-Feel 24s",
    slug: "tc-sublimasi-cotton-feel",
    category: "Merchandise & Flag",
    description: "Kain campuran poliester dan katun lembut dengan ketebalan 24s. Memadukan kemudahan cetak sublimasi cerah anti-luntur dengan handfeel katun alami yang adem di kulit. Sangat diminati produsen kaos distro, polo shirt, dan merchandise event.",
    composition: "65% Polyester, 35% Rayon-Cotton",
    weaveType: "Single Jersey 24s Combed Look",
    widthInch: 72,
    isSublimationReady: true,
    basePricePerMeter: 38000,
    thumbnailUrl: "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?auto=format&fit=crop&w=800&q=80",
    variants: [
      { id: "var-28", gsm: 180, colorName: "Pure White Combed Look", stockMeters: 4800 },
    ],
    priceTiers: [
      { id: "tier-69", minMeters: 1, maxMeters: 49, unitPrice: 38000 },
      { id: "tier-70", minMeters: 50, maxMeters: 199, unitPrice: 34500 },
      { id: "tier-71", minMeters: 200, maxMeters: 999, unitPrice: 31000 },
      { id: "tier-72", minMeters: 1000, maxMeters: undefined, unitPrice: 27500 },
    ],
  },
];

export const MOCK_ORDERS: Order[] = [
  {
    id: "ord-101",
    orderNumber: "TEX-202610-001",
    customerName: "Hendra Wijaya",
    customerCompany: "PT. Garment Kreatif Nusantara",
    customerEmail: "hendra@garmentkreatif.com",
    customerPhone: "081234567890",
    totalAmount: 18500000,
    taxAmount: 2035000,
    shippingAmount: 450000,
    status: "IN_PRODUCTION",
    paymentStatus: "PAID",
    paymentMethod: "BCA Virtual Account",
    trackingNumber: "TRX-KRG-88319",
    createdAt: "2026-10-01 10:30",
    notes: "Batch cetak jersey esport turnamen nasional. Proofing warna disetujui.",
    items: [
      {
        id: "item-1",
        fabricName: "Dryfit Milano Premium",
        gsm: 135,
        lengthMeters: 500,
        unitPrice: 29000,
        subtotal: 14500000,
        customDesignTitle: "Jersey_Esport_Phoenix_Fullprint_Final.ai",
      },
      {
        id: "item-2",
        fabricName: "Scuba Neoprene Stretch Heavy",
        gsm: 260,
        lengthMeters: 100,
        unitPrice: 40000,
        subtotal: 4000000,
        customDesignTitle: "Jacket_Bomber_Sleeve_Pattern.pdf",
      },
    ],
  },
  {
    id: "ord-102",
    orderNumber: "TEX-202610-002",
    customerName: "Sarah Alatas",
    customerCompany: "Alatas Scarves Signature",
    customerEmail: "sarah@alatashijab.id",
    customerPhone: "081822334411",
    totalAmount: 9450000,
    taxAmount: 1039500,
    shippingAmount: 180000,
    status: "QUALITY_CONTROL",
    paymentStatus: "PAID",
    paymentMethod: "Mandiri Bill",
    trackingNumber: "JNE-CARGO-99214",
    createdAt: "2026-10-02 14:15",
    notes: "Koleksi Raya Edition, laser cut packaging.",
    items: [
      {
        id: "item-3",
        fabricName: "Voal Ultrafine Premium Hijab",
        gsm: 85,
        lengthMeters: 300,
        unitPrice: 25000,
        subtotal: 7500000,
        customDesignTitle: "Monogram_Botanical_Autumn_Print.tiff",
      },
      {
        id: "item-4",
        fabricName: "Polyester Silk Satin Silk",
        gsm: 95,
        lengthMeters: 50,
        unitPrice: 39000,
        subtotal: 1950000,
        customDesignTitle: "Square_Scarf_GoldEdition.png",
      },
    ],
  },
  {
    id: "ord-103",
    orderNumber: "TEX-202610-003",
    customerName: "Kevin Suryadi",
    customerCompany: "Runners United Club",
    customerEmail: "kevin@runnersunited.org",
    customerPhone: "087799112233",
    totalAmount: 3250000,
    taxAmount: 357500,
    shippingAmount: 120000,
    status: "PENDING_PAYMENT",
    paymentStatus: "UNPAID",
    paymentMethod: "QRIS Dinamis",
    createdAt: "2026-10-03 09:00",
    notes: "Jersey 10K Fun Run, menunggu konfirmasi transfer bendahara.",
    items: [
      {
        id: "item-5",
        fabricName: "Dryfit Milano Premium",
        gsm: 135,
        lengthMeters: 100,
        unitPrice: 32500,
        subtotal: 3250000,
        customDesignTitle: "10K_MedalRunners_Jersey_FrontBack.pdf",
      },
    ],
  },
  {
    id: "ord-104",
    orderNumber: "TEX-202610-004",
    customerName: "Budi Setiawan",
    customerCompany: "CV. Kreasi Promosi Mandiri",
    customerEmail: "budi@kreasipromosi.com",
    customerPhone: "085611223344",
    totalAmount: 14250000,
    taxAmount: 1567500,
    shippingAmount: 350000,
    status: "SHIPPED",
    paymentStatus: "PAID",
    paymentMethod: "Bank Transfer BCA",
    trackingNumber: "DAKOTA-CARGO-198273",
    createdAt: "2026-09-28 11:20",
    notes: "Telah diserahkan ke kargo logistik roll kain.",
    items: [
      {
        id: "item-6",
        fabricName: "Canvas Polyester 8oz Industrial",
        gsm: 240,
        lengthMeters: 450,
        unitPrice: 31500,
        subtotal: 14175000,
        customDesignTitle: "Totebag_Exhibition_Merchandise.ai",
      },
    ],
  },
];

export const MOCK_LEADS: Lead[] = [
  {
    id: "lead-1",
    title: "Pengadaan Kain Sublimasi Jersey Tim Liga 3 (2.500 Meter)",
    companyName: "PT. Apparel Prima Olahraga",
    contactPerson: "Dimas Anggara (Purchasing Manager)",
    email: "dimas@apparelprima.co.id",
    phone: "081288990011",
    estimatedValue: 68750000,
    estimatedMeters: 2500,
    fabricInterest: "Dryfit Milano 135 GSM",
    stage: "QUOTATION_SENT",
    assignedSalesName: "Rian Pratama",
    updatedAt: "2 Jam lalu",
    activities: [
      {
        id: "act-1",
        leadId: "lead-1",
        authorName: "Rian Pratama",
        type: "SAMPLE_FABRIC_SENT",
        description: "Mengirimkan 3 swatch sampel kain Dryfit Milano 135 GSM dan hasil tes sublimasi warna neon ke kantor Bandung.",
        createdAt: "2026-10-02 11:00",
      },
      {
        id: "act-2",
        leadId: "lead-1",
        authorName: "Rian Pratama",
        type: "PHONE_CALL",
        description: "Telepon dengan Pak Dimas. Sampel diterima dengan baik, warna cyan & magenta sesuai panduan pantone mereka.",
        createdAt: "2026-10-03 14:00",
      },
    ],
  },
  {
    id: "lead-2",
    title: "Koleksi Scarf Hijab Ramadhan Series (1.200 Meter)",
    companyName: "Zahra Hijab Exclusive",
    contactPerson: "Fathia Zahra (Creative Director)",
    email: "fathia@zahrahijab.com",
    phone: "081766554433",
    estimatedValue: 33000000,
    estimatedMeters: 1200,
    fabricInterest: "Voal Ultrafine 85 GSM & Satin Silk",
    stage: "NEGOTIATION",
    assignedSalesName: "Rian Pratama",
    updatedAt: "Kemarin",
    activities: [
      {
        id: "act-3",
        leadId: "lead-2",
        authorName: "Rian Pratama",
        type: "MEETING",
        description: "Meeting online via Google Meet. Klien meminta diskon tambahan 3% untuk komitmen kontrak 3 bulan berturut-turut.",
        createdAt: "2026-10-02 15:30",
      },
    ],
  },
  {
    id: "lead-3",
    title: "Tender Seragam Marathon Korporat Nasional (5.000 Meter)",
    companyName: "Bank Finansial Mandiri Tbk",
    contactPerson: "Siti Rahma (Procurement Div)",
    email: "siti.rahma@bankmandiri.co.id",
    phone: "081199887766",
    estimatedValue: 132500000,
    estimatedMeters: 5000,
    fabricInterest: "Dryfit Milano 135 GSM Quick-Dry",
    stage: "REQUIREMENT_GATHERING",
    assignedSalesName: "Rian Pratama",
    updatedAt: "3 Hari lalu",
    activities: [
      {
        id: "act-4",
        leadId: "lead-3",
        authorName: "Rian Pratama",
        type: "EMAIL",
        description: "Mengirimkan company profile Texora, sertifikasi ramah lingkungan Oeko-Tex tinta sublim, dan portofolio cetak.",
        createdAt: "2026-09-30 09:30",
      },
    ],
  },
  {
    id: "lead-4",
    title: "Pouch & Totebag Sublim Souvenir Konferensi (800 Meter)",
    companyName: "Event Solution Organizer",
    contactPerson: "Ardi Gunawan",
    email: "ardi@eventsolution.co.id",
    phone: "085244332211",
    estimatedValue: 25200000,
    estimatedMeters: 800,
    fabricInterest: "Canvas Polyester 8oz",
    stage: "WON",
    assignedSalesName: "Rian Pratama",
    updatedAt: "Hari ini",
    activities: [
      {
        id: "act-5",
        leadId: "lead-4",
        authorName: "Rian Pratama",
        type: "NOTE",
        description: "PO resmi telah diterbitkan. Uang muka 50% masuk ke rekening BCA. Dilanjutkan ke SPK produksi OMS.",
        createdAt: "2026-10-03 10:00",
      },
    ],
  },
  {
    id: "lead-5",
    title: "Inquiry Cetak Kaos Komunitas Motocross (300 Meter)",
    companyName: "Komunitas Enduro Jakarta",
    contactPerson: "Rangga Pratama",
    email: "rangga@endurojkt.club",
    phone: "087811223344",
    estimatedValue: 9750000,
    estimatedMeters: 300,
    fabricInterest: "Dryfit Heavy 155 GSM",
    stage: "NEW_INQUIRY",
    assignedSalesName: "Rian Pratama",
    updatedAt: "10 Menit lalu",
    activities: [],
  },
];

export const MOCK_INVENTORY: InventoryRoll[] = [
  {
    id: "inv-1",
    rollBarcode: "ROL-DFM-135-0981",
    fabricName: "Dryfit Milano Premium",
    gsm: 135,
    initialMeters: 100,
    currentMeters: 74,
    warehouseLocation: "Zona A - Rak 03 - Tier 2",
    batchLot: "LOT-2026-09B",
    receivedDate: "2026-09-15",
  },
  {
    id: "inv-2",
    rollBarcode: "ROL-DFM-135-0982",
    fabricName: "Dryfit Milano Premium",
    gsm: 135,
    initialMeters: 100,
    currentMeters: 100,
    warehouseLocation: "Zona A - Rak 03 - Tier 3",
    batchLot: "LOT-2026-09B",
    receivedDate: "2026-09-15",
  },
  {
    id: "inv-3",
    rollBarcode: "ROL-STN-095-0412",
    fabricName: "Polyester Silk Satin Silk",
    gsm: 95,
    initialMeters: 80,
    currentMeters: 28,
    warehouseLocation: "Zona B - Rak 01 - Tier 1",
    batchLot: "LOT-2026-08A",
    receivedDate: "2026-08-20",
  },
  {
    id: "inv-4",
    rollBarcode: "ROL-SCB-260-0199",
    fabricName: "Scuba Neoprene Stretch Heavy",
    gsm: 260,
    initialMeters: 60,
    currentMeters: 55,
    warehouseLocation: "Zona C - Palet 04",
    batchLot: "LOT-2026-09D",
    receivedDate: "2026-09-24",
  },
  {
    id: "inv-5",
    rollBarcode: "ROL-VOL-085-1102",
    fabricName: "Voal Ultrafine Premium Hijab",
    gsm: 85,
    initialMeters: 120,
    currentMeters: 120,
    warehouseLocation: "Zona B - Rak 04 - Tier 2",
    batchLot: "LOT-2026-10A",
    receivedDate: "2026-10-01",
  },
];
